version: '2'

services:

  expert:
    image: ayanozturk/expert:latest
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:80"
    depends_on:
      - expert-mysql
    environment:
      EXPERT_ENV: dev
      BROWSERSTACK_USERNAME: USERNAME
      BROWSERSTACK_ACCESS_KEY: ACCESS_KEY

  expert-mysql:
    image: mysql:5
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: expert

  selenium:
    image: elgalu/selenium:latest
    ports:
      - 4444:24444
      - 5900:25900
