app:
    resource: '@AppBundle/Controller/'
    type: annotation

# ---------------------------------------------
# Security
# ---------------------------------------------
login:
    path:      /login
    defaults:  { _controller: AppBundle:Security:Login }

logout:
    path: /logout
