app:
    resource: '@AppBundle/Controller/'
    type: annotation

# ---------------------------------------------
# Security
# ---------------------------------------------
login:
    path:      /login
    defaults:  { _controller: AppBundle:Security:Login }

logout:
    path: /logout

register:
    path:     /register
    defaults: { _controller: AppBundle:Security:Register }

profile:
    path:     /profile/{user_id}
    defaults: { _controller: AppBundle:User:Profile }

# ---------------------------------------------
# API
# ---------------------------------------------
api_skills:
    type:     rest
    resource: AppBundle\Controller\SkillController
